<a href="https://colab.research.google.com/github/Harshitnitw/ML_FinalYearProject/blob/main/LinearModelWithOHE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('data.csv')
df

    time  inlet temparature  moisture ratio food sample
0    0.0                 32        1.000000       guava
1    1.0                 35        0.946000       guava
2    2.0                 36        0.864750       guava
3    3.0                 41        0.738750       guava
4    4.0                 43        0.581750       guava
5    5.0                 44        0.477750       guava
6    6.0                 45        0.399250       guava
7    7.0                 43        0.352500       guava
8    8.0                 40        0.336000       guava
9    9.0                 39        0.323500       guava
10  10.0                 31        0.323500       guava
11  11.0                 33        0.307500       guava
12  12.0                 36        0.286250       guava
13  13.0                 41        0.264500       guava
14  14.0                 43        0.223000       guava
15  15.0                 44        0.193500       guava
16  16.0                 45        0.176250       guava
17  17.0                 43        0.166500       guava
18  18.0                 40        0.159750       guava
19  19.0                 39        0.156750       guava
20   0.0                 29        1.000000   muskmelon
21   1.0                 31        0.937250   muskmelon
22   2.0                 34        0.879875   muskmelon
23   3.0                 37        0.754250   muskmelon
24   4.0                 41        0.599750   muskmelon
25   5.0                 42        0.493500   muskmelon
26   6.0                 41        0.412000   muskmelon
27   7.0                 40        0.342000   muskmelon
28   8.0                 39        0.298750   muskmelon
29   9.0                 38        0.266250   muskmelon
30  10.0                 29        0.266250   muskmelon
31  11.0                 32        0.250750   muskmelon
32  12.0                 36        0.228500   muskmelon
33  13.0                 38        0.204000   muskmelon
34  14.0                 41        0.160500   muskmelon
35  15.0                 42        0.122500   muskmelon
36  16.0                 41        0.098250   muskmelon
37  17.0                 41        0.091500   muskmelon
38  18.0                 40        0.087000   muskmelon
39  19.0                 38        0.086500   muskmelon
40   0.0                 29        1.000000    beetroot
41   1.0                 32        0.971500    beetroot
42   2.0                 34        0.909750    beetroot
43   3.0                 38        0.816875    beetroot
44   4.0                 41        0.706625    beetroot
45   5.0                 43        0.603625    beetroot
46   6.0                 42        0.523625    beetroot
47   7.0                 42        0.453000    beetroot
48   8.0                 41        0.398125    beetroot
49   9.0                 39        0.365625    beetroot
50  10.0                 29        0.365625    beetroot
51  11.0                 32        0.331875    beetroot
52  12.0                 35        0.272875    beetroot
53  13.0                 38        0.212125    beetroot
54  14.0                 41        0.172250    beetroot
55  15.0                 43        0.147750    beetroot
56  16.0                 42        0.134625    beetroot
57  17.0                 41        0.126750    beetroot
58  18.0                 41        0.123500    beetroot
59  19.0                 39        0.120750    beetroot

In [7]:
dummies = pd.get_dummies(df['food sample'])
dummies

    beetroot  guava  muskmelon
0          0      1          0
1          0      1          0
2          0      1          0
3          0      1          0
4          0      1          0
5          0      1          0
6          0      1          0
7          0      1          0
8          0      1          0
9          0      1          0
10         0      1          0
11         0      1          0
12         0      1          0
13         0      1          0
14         0      1          0
15         0      1          0
16         0      1          0
17         0      1          0
18         0      1          0
19         0      1          0
20         0      0          1
21         0      0          1
22         0      0          1
23         0      0          1
24         0      0          1
25         0      0          1
26         0      0          1
27         0      0          1
28         0      0          1
29         0      0          1
30         0      0          1
31         0      0          1
32         0      0          1
33         0      0          1
34         0      0          1
35         0      0          1
36         0      0          1
37         0      0          1
38         0      0          1
39         0      0          1
40         1      0          0
41         1      0          0
42         1      0          0
43         1      0          0
44         1      0          0
45         1      0          0
46         1      0          0
47         1      0          0
48         1      0          0
49         1      0          0
50         1      0          0
51         1      0          0
52         1      0          0
53         1      0          0
54         1      0          0
55         1      0          0
56         1      0          0
57         1      0          0
58         1      0          0
59         1      0          0

In [8]:
merged = pd.concat([df,dummies],axis='columns')

In [9]:
final = merged.drop(['food sample','muskmelon'],axis='columns')
final

    time  inlet temparature  moisture ratio  beetroot  guava
0    0.0                 32        1.000000         0      1
1    1.0                 35        0.946000         0      1
2    2.0                 36        0.864750         0      1
3    3.0                 41        0.738750         0      1
4    4.0                 43        0.581750         0      1
5    5.0                 44        0.477750         0      1
6    6.0                 45        0.399250         0      1
7    7.0                 43        0.352500         0      1
8    8.0                 40        0.336000         0      1
9    9.0                 39        0.323500         0      1
10  10.0                 31        0.323500         0      1
11  11.0                 33        0.307500         0      1
12  12.0                 36        0.286250         0      1
13  13.0                 41        0.264500         0      1
14  14.0                 43        0.223000         0      1
15  15.0                 44        0.193500         0      1
16  16.0                 45        0.176250         0      1
17  17.0                 43        0.166500         0      1
18  18.0                 40        0.159750         0      1
19  19.0                 39        0.156750         0      1
20   0.0                 29        1.000000         0      0
21   1.0                 31        0.937250         0      0
22   2.0                 34        0.879875         0      0
23   3.0                 37        0.754250         0      0
24   4.0                 41        0.599750         0      0
25   5.0                 42        0.493500         0      0
26   6.0                 41        0.412000         0      0
27   7.0                 40        0.342000         0      0
28   8.0                 39        0.298750         0      0
29   9.0                 38        0.266250         0      0
30  10.0                 29        0.266250         0      0
31  11.0                 32        0.250750         0      0
32  12.0                 36        0.228500         0      0
33  13.0                 38        0.204000         0      0
34  14.0                 41        0.160500         0      0
35  15.0                 42        0.122500         0      0
36  16.0                 41        0.098250         0      0
37  17.0                 41        0.091500         0      0
38  18.0                 40        0.087000         0      0
39  19.0                 38        0.086500         0      0
40   0.0                 29        1.000000         1      0
41   1.0                 32        0.971500         1      0
42   2.0                 34        0.909750         1      0
43   3.0                 38        0.816875         1      0
44   4.0                 41        0.706625         1      0
45   5.0                 43        0.603625         1      0
46   6.0                 42        0.523625         1      0
47   7.0                 42        0.453000         1      0
48   8.0                 41        0.398125         1      0
49   9.0                 39        0.365625         1      0
50  10.0                 29        0.365625         1      0
51  11.0                 32        0.331875         1      0
52  12.0                 35        0.272875         1      0
53  13.0                 38        0.212125         1      0
54  14.0                 41        0.172250         1      0
55  15.0                 43        0.147750         1      0
56  16.0                 42        0.134625         1      0
57  17.0                 41        0.126750         1      0
58  18.0                 41        0.123500         1      0
59  19.0                 39        0.120750         1      0

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [12]:
X = final.drop('moisture ratio', axis='columns')
X

    time  inlet temparature  beetroot  guava
0    0.0                 32         0      1
1    1.0                 35         0      1
2    2.0                 36         0      1
3    3.0                 41         0      1
4    4.0                 43         0      1
5    5.0                 44         0      1
6    6.0                 45         0      1
7    7.0                 43         0      1
8    8.0                 40         0      1
9    9.0                 39         0      1
10  10.0                 31         0      1
11  11.0                 33         0      1
12  12.0                 36         0      1
13  13.0                 41         0      1
14  14.0                 43         0      1
15  15.0                 44         0      1
16  16.0                 45         0      1
17  17.0                 43         0      1
18  18.0                 40         0      1
19  19.0                 39         0      1
20   0.0                 29         0      0
21   1.0                 31         0      0
22   2.0                 34         0      0
23   3.0                 37         0      0
24   4.0                 41         0      0
25   5.0                 42         0      0
26   6.0                 41         0      0
27   7.0                 40         0      0
28   8.0                 39         0      0
29   9.0                 38         0      0
30  10.0                 29         0      0
31  11.0                 32         0      0
32  12.0                 36         0      0
33  13.0                 38         0      0
34  14.0                 41         0      0
35  15.0                 42         0      0
36  16.0                 41         0      0
37  17.0                 41         0      0
38  18.0                 40         0      0
39  19.0                 38         0      0
40   0.0                 29         1      0
41   1.0                 32         1      0
42   2.0                 34         1      0
43   3.0                 38         1      0
44   4.0                 41         1      0
45   5.0                 43         1      0
46   6.0                 42         1      0
47   7.0                 42         1      0
48   8.0                 41         1      0
49   9.0                 39         1      0
50  10.0                 29         1      0
51  11.0                 32         1      0
52  12.0                 35         1      0
53  13.0                 38         1      0
54  14.0                 41         1      0
55  15.0                 43         1      0
56  16.0                 42         1      0
57  17.0                 41         1      0
58  18.0                 41         1      0
59  19.0                 39         1      0

In [13]:
y=final['moisture ratio']

In [ ]:
model.fit()

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [14]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [22]:
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
model.score(X_test, y_test)
lr_MSE=mean_squared_error(y_test, y_pred)
lr_MAE= mean_absolute_error(y_test, y_pred)
lr_RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
lr_R2=r2_score(y_test, y_pred)

In [23]:
results = pd.DataFrame({'Algorithm':['Linear Regression Method'],'R2':[lr_R2] , 'MAE':[lr_MAE], 'MSE':[lr_MSE], 'RMSE':[lr_RMSE] })
results

                  Algorithm        R2       MAE       MSE      RMSE
0  Linear Regression Method  0.930986  0.082316  0.008892  0.094299